language: python
python:
  - "3.6"
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=3.7.3
install:
  - pip install -r requirements.txt
before_script:
  - docker-compose up --build -d
script:
  - python test_script.py
after_script:
  - docker-compose down